db:
    restart: always
    image: postgres
    environment:
        - POSTGRES_USER=secure_messenger_app
        - POSTGRES_PASSWORD=a_changer
        - POSTGRES_DB=secure_messenger_db
    volumes:
      - ./sql/2-tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  